export const CONFIG = {
  ANIMATION: {
    SPRITE_SPEED: 0.25,
    SIZE_MULTIPLIER: 2.7,
    FADE_DURATION: 0.5,
    PULSE_SCALE: 1.12,
    PULSE_DURATION: 0.8,
    HOVER_SCALE: 1.2,
    HOVER_DURATION: 0.3,
    SELECTED_SCALE: 1.5,
    DIM_SCALE: 0.7,
    FLY_AWAY_DELAY: 0.3,
    FLY_AWAY_BOUNCE: "5vh",
    FLY_AWAY_DISTANCE: "120vh",
    FLY_AWAY_BOUNCE_DURATION: 0.2,
    FLY_AWAY_DURATION: 0.8,
  },
  PARTICLES: {
    SPARKLE_COUNT: 20,
    FOG_COUNT: 50,
    TARGET_FPS: 25,
  },
  SPARKLES: {
    COLORS: [
      { main: 0xffb6c1, glow: 0xff69b4 },
      { main: 0xadd8e6, glow: 0x87ceeb },
      { main: 0xffff99, glow: 0xffd700 },
    ],
    ANIMATION: {
      SCREEN_CHECK_INTERVAL: 500,
      PERFORMANCE_THRESHOLD: 16,
    },
    SPARKLE: {
      ELLIPSE_WIDTH: 15,
      ELLIPSE_HEIGHT: 3,
      SPEED_MIN: 2,
      SPEED_MAX: 5,
      SIZE_MIN: 1.5,
      SIZE_MAX: 4.5,
      LENGTH_MIN: 7,
      LENGTH_MAX: 17,
      OPACITY_MIN: 0.4,
      OPACITY_MAX: 1.0,
      LIFE_SPEED_MIN: 0.005,
      LIFE_SPEED_MAX: 0.015,
      DEPTH_MIN: 0.5,
      DEPTH_MAX: 1.0,
      LIFE_OPACITY_MULTIPLIER: 0.3,
      LIFE_OPACITY_BASE: 0.7,
      SCALE_DIVISOR_X: 2,
      SCALE_DIVISOR_Y: 3,
      BASE_ELLIPSE_SIZE: 15,
    },
    FOG: {
      TEXTURE_SIZE: 150,
      BLUR_FILTER: 4,
      PARTICLE_COUNT_MAX: 15,
      CENTER_Y_BASE: 0.7,
      CENTER_Y_RANGE: 0.1,
      POSITION_RANGE_X: 500,
      POSITION_OFFSET_X: 250,
      POSITION_RANGE_Y: 300,
      POSITION_OFFSET_Y: 150,
      ALPHA_MIN: 0.2,
      ALPHA_MAX: 0.35,
      SPEED_MIN: -50,
      SPEED_MAX: 50,
      SPEED_DIVISOR: 10000,
      DURATION_MIN: 20,
      DURATION_MAX: 50,
      DISTANCE_MULTIPLIER_X: 0.8,
      DISTANCE_MULTIPLIER_Y: 0.8,
      ALPHA_ANIMATION_MIN: 0.1,
      ALPHA_ANIMATION_MAX: 0.25,
      ALPHA_DURATION_MIN: 3,
      ALPHA_DURATION_MAX: 7,
      SCALE_MIN: 0.4,
      SCALE_MAX: 0.8,
      SCALE_MULTIPLIER: 1.2,
      SCALE_DURATION_MIN: 4,
      SCALE_DURATION_MAX: 7,
      TICKER_SPEED: 0.3,
      TINTS: [
        0xff4500, 0xff6600, 0xffaa00, 0xff0000, 0xff8800, 0xffcc00, 0xff5500,
        0xff9900,
      ],
    },
    FOG_TEXTURE: {
      SIZE: 150,
      CIRCLE_COUNT: 8,
      RADIUS_MULTIPLIER_MIN: 0.2,
      RADIUS_MULTIPLIER_MAX: 0.7,
      POSITION_OFFSET_MULTIPLIER: 0.4,
      ALPHA_MIN: 0.01,
      ALPHA_MAX: 0.025,
      TINTS: [0x1e88e5, 0x42a5f5, 0x64b5f6, 0x90caf9, 0x2196f3, 0x0d47a1],
    },
  },
  WIN: {
    DEFAULT_AMOUNT: "100$ + 5 FREE SPINS",
    MIN_SMALL: 10,
    MAX_SMALL: 50,
    MIN_LARGE: 100,
    MAX_LARGE: 10000,
    BIG_WIN_BONUS: 5000,
  },
  BIG_WIN_SCREEN: {
    PANEL_FADE_DURATION: 0.5,
    SCREEN_ANIMATION: {
      DURATION: 0.5,
      EASE: "back.out(1.7)",
      CONTENT_DELAY: 600,
      CONTENT_DURATION: 0.6,
      CONTENT_EASE: "back.out(1.5)",
      FADE_OUT_DURATION: 0.5,
      FADE_OUT_SCALE: 0.8,
      FADE_OUT_EASE: "power2.in",
    },
    BALANCE_ANIMATION: {
      DURATION: 3,
      EASE: "power1.out",
      WAIT_AFTER: 1000,
    },
    EXPLOSION: {
      CANVAS_SIZE: 800,
      CONTAINER_SIZE: "200vw",
      CONTAINER_HEIGHT: "200vh",
    },
    VOLCANO: {
      WRAPPER_WIDTH: "clamp(25rem, 60vw, 50rem)",
      WRAPPER_HEIGHT: "clamp(20rem, 50vh, 40rem)",
      WRAPPER_TRANSFORM_Y: "clamp(-12rem, -18vh, -10rem)",
      GLOW_SIZE: "clamp(12rem, 30vw, 24rem)",
      GLOW_BLUR: "clamp(0.8rem, 2vw, 1.5rem)",
      FIRE_TOP: "-30%",
      FIRE_HEIGHT: "90%",
      FIRE_TRANSLATE_Y: "-50px",
      FIRE_BLUR: "8px",
    },
    BANNER: {
      TOP: "55%",
      GAP: "clamp(1rem, 2vh, 1.5rem)",
      WIDTH: "clamp(26rem, 75vw, 60rem)",
      MARGIN_TOP: "clamp(8rem, 15vh, 12rem)",
    },
    AMOUNT: {
      TOP: "40%",
      FONT_SIZE: "clamp(2rem, 6vw, 4rem)",
      TEXT_SHADOW:
        "0.15rem 0.15rem 0.4rem rgba(0, 0, 0, 1), 0 0 1rem rgba(255, 255, 255, 0.8)",
    },
    Z_INDEX: {
      SCREEN: 1000,
      EXPLOSION: 1,
      CONTENT: 2,
      VOLCANOES_SECTION: 2,
      GLOW: 0,
      FIRE: -1,
      VOLCANO_IMAGE: 1,
      BANNER: 1001,
      COINS_CANVAS: 999,
      BALANCE_COINS_CANVAS: 1002,
    },
    GLOW: {
      GRADIENT_COLORS: [
        { r: 255, g: 215, b: 0, a: 0.6 },
        { r: 255, g: 215, b: 0, a: 0.4 },
        { r: 255, g: 215, b: 0, a: 0.2 },
        { r: 255, g: 215, b: 0, a: 0 },
      ],
      GRADIENT_STOPS: ["0%", "30%", "60%", "100%"],
    },
    VOLCANO_ANIMATION: {
      ERUPTION: {
        INITIAL_DELAY_MIN: 1,
        INITIAL_DELAY_MAX: 2,
        NEXT_DELAY_MIN: 3,
        NEXT_DELAY_MAX: 4,
        GLOW_SCALE: 1.2,
        GLOW_OPACITY: 1,
        GLOW_DURATION: 0.2,
        GLOW_FADE_DURATION: 0.8,
        GLOW_FADE_OFFSET: -0.5,
        FIRE_OPACITY: 1,
        FIRE_DURATION: 0.2,
        FIRE_FADE_DURATION: 0.8,
        FIRE_FADE_OFFSET: -0.5,
        VOLCANO_SCALE_X_1: 1.1,
        VOLCANO_SCALE_X_2: 0.95,
        VOLCANO_SCALE_Y: 1.15,
        VOLCANO_DURATION_1: 0.2,
        VOLCANO_DURATION_2: 0.3,
        VOLCANO_DURATION_3: 0.5,
        EASE_OUT: "power2.out",
        EASE_IN: "power2.in",
      },
    },
    COIN_EXPLOSION: {
      SPRITESHEET: {
        COLS: 4,
        ROWS: 2,
      },
      ANIMATION_SPEED: 0.3,
      PER_VOLCANO: {
        MIN: 6,
        MAX: 8,
      },
      SCALE: {
        MIN: 0.065,
        MAX: 0.13,
      },
      SPEED: {
        MIN: 3,
        MAX: 4,
      },
      VELOCITY_Y: -3,
      GRAVITY: 0.3,
      ROTATION_SPEED_MULTIPLIER: 0.15,
      FADE_START_TIME: 0.6,
      DURATION: 2000,
      BOUNDARY_OFFSET: 100,
    },
    BALANCE_COIN_EXPLOSION: {
      SPRITESHEET: {
        COLS: 4,
        ROWS: 2,
      },
      ANIMATION_SPEED: 0.3,
      COUNT: {
        MIN: 12,
        MAX: 19,
      },
      SCALE: {
        MIN: 0.1,
        MAX: 0.13,
      },
      SPEED: {
        MIN: 3,
        MAX: 4,
      },
      VELOCITY_Y: -1.5,
      GRAVITY: 0.3,
      ROTATION_SPEED_MULTIPLIER: 0.2,
      ANGLE_RANDOM: 0.3,
      START_DELAY_MAX: 200,
      FADE_START_TIME: 1.5,
      DURATION: 3000,
      INTERVAL: 300,
      BOUNDARY_OFFSET: 100,
    },
    CONTENT_GAP: "clamp(4rem, 10vh, 8rem)",
  },
  ZIGZAG_OUTLINE: {
    VERTICAL_PADDING_MULTIPLIER: 0.3,
    RIGHT_TRIM_MULTIPLIER: 0.04,
    ZIGZAG_SIZE_MAX: 25,
    ZIGZAG_SIZE_DIVISOR: 6,
    PADDING: 10,
    CORNER_RADIUS_MAX: 20,
    CORNER_RADIUS_DIVISOR: 8,
    SEGMENT_MULTIPLIER: 1.5,
    RANDOM_OFFSET_MULTIPLIER: 0.6,
    STROKE_WIDTH: 4,
    STROKE_WIDTH_SECONDARY: 2,
    SECONDARY_OPACITY: 0.6,
    BLUR_STD_DEVIATION: 4,
    Z_INDEX: 100,
    ANIMATION: {
      FADE_IN_DURATION: 0.5,
      FADE_IN_SCALE: 0.95,
      FADE_IN_EASE: "power2.out",
      DRAW_DURATION: 0.8,
      DRAW_EASE: "power2.out",
      DRAW_DELAY: 0.2,
      DRAW_DELAY_SECONDARY: 0.3,
      PULSE_DURATION: 1.5,
      PULSE_EASE: "sine.inOut",
      PULSE_OPACITY: 0.3,
      PULSE_OPACITY_DURATION: 0.15,
      PULSE_STROKE_WIDTH: 6,
      PULSE_STROKE_WIDTH_DURATION: 0.3,
    },
    GRADIENT: {
      COLORS: ["#ffffff", "#ffff00", "#ffa500"],
      STOPS: ["0%", "50%", "100%"],
    },
  },
  TIMING: {
    LOADING_DELAY: 500,
    SPARKLES_DELAY: 1500,
    CHEST_OPEN_DELAY: 300,
    FLY_AWAY_DELAY: 1000,
    CHEST_ANIMATION_CLEANUP_DELAY: 2000,
    TRANSITION_CLEANUP_DELAY: 100,
    TRANSITION_FADE_DURATION: 0.5,
  },
  CHEST_ANIMATION: {
    SPRITESHEET: {
      COLS: 5,
      ROWS: 3,
    },
    CANVAS: {
      FALLBACK_SIZE: 200,
      TARGET_FPS: 60,
      FRAME_INTERVAL: 1000 / 60,
    },
    SPRITE: {
      START_Y_OFFSET: 0.15,
      INITIAL_ALPHA: 0,
      FINAL_ALPHA: 1,
      INITIAL_SCALE: 0.3,
      FINAL_SCALE: 1,
    },
    WIN_INDICATOR: {
      MIN_TOP_REM: -18,
      MAX_TOP_REM: -20,
      VIEWPORT_MULTIPLIER: 0.45,
      MIN_Y_REM: 15,
      MAX_Y_REM: 20,
      VH_MULTIPLIER: 40,
      ANIMATION_DURATION: 0.3,
      EASE: "sine.out",
    },
    CLEANUP_DELAY: 2000,
  },
  CHEST_COIN_EXPLOSION: {
    SPRITESHEET: {
      COLS: 4,
      ROWS: 2,
    },
    CANVAS: {
      Z_INDEX: 999,
      RESOLUTION_MAX: 1.5,
    },
    COINS: {
      COUNT_MIN: 6,
      COUNT_MAX: 10,
      ANIMATION_SPEED: 0.3,
      SCALE_MIN: 0.08,
      SCALE_MAX: 0.1,
      SPEED_MIN: 2,
      SPEED_MAX: 5,
      VELOCITY_Y: -2,
      GRAVITY: 0.3,
      ROTATION_SPEED_MULTIPLIER: 0.15,
      ANGLE_RANDOM: 0.5,
      FADE_START_TIME: 0.6,
      DURATION: 2000,
      BOUNDARY_OFFSET: 100,
      CLEANUP_DELAY: 500,
    },
  },
  BIG_WIN_COIN_EXPLOSION: {
    SPRITESHEET: {
      COLS: 4,
      ROWS: 2,
    },
    CANVAS: {
      Z_INDEX: 998,
      RESOLUTION_MAX: 1.5,
    },
    COINS: {
      COUNT_MIN: 15,
      COUNT_MAX: 25,
      ANIMATION_SPEED: 0.3,
      SCALE_MIN: 0.1,
      SCALE_MAX: 0.15,
      SPEED_MIN: 3,
      SPEED_MAX: 7,
      VELOCITY_Y: -1,
      GRAVITY: 0.3,
      ROTATION_SPEED_MULTIPLIER: 0.15,
      ANGLE_RANDOM: 0.8,
      FADE_START_TIME: 0.5,
      DURATION: 2500,
      BOUNDARY_OFFSET: 100,
      CLEANUP_DELAY: 500,
    },
  },
  TRANSITION: {
    PANEL_ANIMATION: {
      LEFT_DELAY: 0,
      CENTER_DELAY: 0.1,
      RIGHT_DELAY: 0.2,
    },
  },
  SLOT_MACHINE: {
    COLUMNS: 4,
    ROWS: 4,
    SPIN_DURATION: 1.5,
    STOP_DELAY: 100,
    BOUNCE_HEIGHT: "5vh",
    SYMBOL_SCALE_DURATION: 0.3,
    BIG_WIN_DISPLAY_DURATION: 5000,
    NORMAL_WIN_DISPLAY_DURATION: 2000,
    COIN_RAIN_PARTICLES: 30,
    COIN_RAIN_DURATION: 3000,
    SPIN_SYMBOL_CHANGE_INTERVAL: 50,
    SPIN_CYCLES: 45,
    COLUMN_START_DELAY: 100,
    COLUMN_HEIGHT_FALLBACK: 400,
    COLUMN_DURATION_INCREMENT: 0.1,
    BLUR_FADE_START: 0.6,
    BLUR_FADE_RANGE: 0.4,
    SYMBOL_DELAY_MULTIPLIER: 0.05,
    SYMBOL_GAP: "clamp(0.5rem, 1vw, 1rem)",
    ADDITIONAL_WAIT_DELAY: 100,
    COIN_ANIMATION: {
      DELAY_MULTIPLIER: 0.1,
      FIRE_OPACITY_DURATION: 0.2,
      SCALE_UP_DURATION: 0.4,
      SCALE_DOWN_DURATION: 0.4,
      FIRE_FADE_DURATION: 0.3,
      SCALE_UP_VALUE: 2,
      EASE_BACK_OUT: "back.out(1.5)",
      EASE_BACK_IN: "back.in(1.2)",
    },
    COIN_VALUES: [2, 3, 5],
  },
  VOLCANO: {
    SPRITE_SPEED: 0.2,
    FRAMES: 15,
    COLS: 5,
    ROWS: 3,
  },
  JOKER_WIN: {
    SPRITE_SPEED: 0.18,
    FRAMES: 16,
    COLS: 4,
    ROWS: 4,
  },
  SLOT_WINS: {
    JOKER_4: { amount: 14800, type: "BIG_WIN" },
    COIN_10_4: { amount: 40 },
    COIN_10_3: { amount: 30 },
    COIN_5_4: { amount: 20 },
    COIN_5_3: { amount: 15 },
    COIN_3_4: { amount: 12 },
    COIN_3_3: { amount: 9 },
    COIN_2_4: { amount: 8 },
    COIN_2_3: { amount: 6 },
  },
  UI_ANIMATION: {
    ENTRY_FROM_LEFT_DURATION: 0.8,
    ENTRY_FROM_BOTTOM_DURATION: 1,
    ENTRY_FROM_RIGHT_DURATION: 0.8,
    ENTRY_STAGGER: 0.1,
  },
  CTA: {
    STORE_URL: "https://apps.apple.com/app/coin-volcanoes",
    INSTALL_DELAY: 500,
  },
  EXPLOSION: {
    SPRITE_SPEED: 0.5,
    FRAMES: 7,
    COLS: 7,
    ROWS: 1,
  },
  CURSOR: {
    INTERACTIVE_ELEMENTS: [
      ".withdraw-button",
      ".refresh-button",
      ".balance-billboard",
      ".free-spins-billboard",
      ".jackpot-mini",
      ".jackpot-major",
      ".jackpot-minor",
    ],
  },
  TRACKING: {
    CLICKABLE_ELEMENTS: [
      ".withdraw-button",
      ".refresh-button",
      ".chest-wrapper",
      ".play-now-button",
    ],
  },
  COIN_SPARKS: {
    COUNT: 12,
    MIN_DISTANCE: 30,
    MAX_DISTANCE: 80,
    MIN_SIZE: 0.75,
    MAX_SIZE: 1.25,
    MIN_DURATION: 0.6,
    MAX_DURATION: 0.9,
    ANGLE_VARIATION: 0.8,
    CLEANUP_DELAY: 1000,
  },
  VOLCANO_ERUPTION: {
    FLAME_COUNT: 3,
    SMOKE_COUNT: 8,
    DELAYS: {
      LEFT: 0,
      CENTER: 1,
      RIGHT: 2,
    },
    INITIAL_DELAY_VARIATION: 2,
    NEXT_DELAY_MIN: 3,
    NEXT_DELAY_MAX: 7,
    LEFT_OFFSET_X: 20,
    LEFT_OFFSET_Y: -50,
    GLOW_SCALE: 1.2,
    VOLCANO_SCALE: 1.15,
    ANIMATION: {
      GLOW_DURATION: 0.2,
      FIRE_DURATION: 0.2,
      VOLCANO_EXPAND_DURATION: 0.3,
      VOLCANO_CONTRACT_DURATION: 0.5,
      FADE_DURATION: 0.4,
    },
  },
  JACKPOTS: [
    { type: "mini", amount: 22000 },
    { type: "major", amount: 69000 },
    { type: "minor", amount: 36000 },
  ],
  JACKPOT_COUNTER: {
    UPDATE_INTERVAL: 50,
    LOCALE: "ru-RU",
    CURRENCY_SYMBOL: "€",
    PERFORMANCE_THRESHOLD: 16,
  },
};
